### ISSUE TITLE
Escaping of XML strings is not correct

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-xml#1]
The escaping of XML strings is not correct. This affects the "<" and ">". They are swapped. The actual formatting of the original code makes the issue obvious. 

**Current escaping:**

/**
 escape xml
 */
public func escapeXml(text: String) -> String {
    return text.replacingOccurrences(of: "&", with: "&amp;")
      .replacingOccurrences(of: "<", with: &gt;)
      .replacingOccurrences(of: ">", with: "&lt;")
}

/**
 unescape xml
 */
public func unescapeXml(text: String) -> String {
    return text.replacingOccurrences(of: &gt;, with: "<")
      .replacingOccurrences(of: &lt;, with: ">")
      .replacingOccurrences(of: "&amp;", with: "&")
}

**This is a known correct escaping:**

    static let uriEscapedDictionary = [
        "&amp;": "&",
        "&quot;" : "\"",
        "&#x27;" : "'",
        "&#x39;" : "'",
        "&#x92;" : "'",
        "&#x96;" : "'",
        ""&gt;"" : ">",
       "&lt;" : "<"]
    
    static let htmlEscapedDictionary = [
        "&gt;" : ">",
        "&lt;" : "<"]

**Comment by bjtj** [comment]
Thank you!

I fixed it (tag [0.1.10](https://github.com/bjtj/swift-xml/releases/tag/0.1.10))

commit: https://github.com/bjtj/swift-xml/commit/fafa084a6e8e87c16106da9791389cb689767f2b

**Comment by meisbedi** [comment]
I tested the updated version and the fix is effective. Thank you for the fast reaction
