### ISSUE TITLE
parser cannot handle incomplete tags

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-xml#2]
During testing of upnp-tools I came across a device that was sending event messages with an incomplete tag.
There were only opening tag statements, no tag data and not tag closing statements. This situation leads to a crash of the parser, because the parser seems to assume, that there are always complete tags.

The following portion of the function is affected:

             } else if isEndTag(text: token.text) {
                   if cursor!.parent == nil {
                        document.rootElement = cursor as? XmlElement
                        return document
                    }
                    cursor = cursor!.parent
            } else if isAtomTag(text: token.text) {

if the condition isEndTag is true, the function assumes, that cursor is not nil. But if there are no closing tag statements, the cursor variable is nil, and the app crashes. If I check the cursor variable for nil and return an empty document, if cursor is nil, than I can avoid the crash. The empty document is no problem, because in this specific case, there is no actual information inside the xml data. I did not drill deep enough into the parser function to recognise, if there might be a way to leave only the incorrect tag affected.

**Comment by bjtj** [comment]
Thanks!
