### ISSUE TITLE
Token with values/attributes that contain a xml string are not properly recognised

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-xml#3]
A standard UPnP player uses eventing to report status changes of the transport service. Due to the structure of the event data, xml metadata are reported from the transport as a value/attribute of the "Last Change" variable/token. The current implementation of swift-xml cannot handle this configuration. I have adapted the tokenize and the parseTag functions to deal with this configuration.

tokenize function from the XMLTokenizer module:

    public static func tokenize(text: String) throws -> [Token] {
        var tokens = [Token]()
        var str = ""
        var intag = false
        var inval = false
        var inComment = false
        for char in text {
            if !intag && char == "<" {
                intag = true
                if str.isEmpty == false && str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == false {
                    tokens.append(Token(type: .text, text: str))
                }
                str = "<"
                continue
            }

            if !inComment && intag && str.hasPrefix("<!--") {
                inComment = true
            }

            if inComment && !(str.hasSuffix("--") && char == ">") {
                str.append(char)
                continue
            }

            if inComment && (str.hasSuffix("--") && char == ">") {
                intag = false
                inComment = false
                str.append(char)
                tokens.append(Token(type: .tag, text: str))
                str = ""
                continue
            }
            
            if intag && !inval && str.contains("val=\"<") {
                inval = true
            }
            
            if intag && inval && str.contains(">\"/") {
                inval = false
            }

            if intag && !inval && char == ">" {
                intag = false
                inComment = false
                inval = false
                str.append(char)
                tokens.append(Token(type: .tag, text: str))
                str = ""
                continue
            }

            str.append(char)
        }
        guard str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw XmlParseError.unexpectedEos(reason: "str -> '\(str)'")
        }
        return tokens
    }

parseTag function from the XmlParser module

    static func parseTag(text: String) -> XmlElement {
        let sub = text
        var tokens = [String]()
        var escape = false
        var inQuote = false
        var inBrace = false
        var str = ""
        for char in sub {
            if escape == true {
                switch char {
                case "n":
                    str.append("\n")
                case "r":
                    str.append("\r")
                case "t":
                    str.append("\t")
                default:
                    str.append(char)
                }
                escape = false
            } else if inQuote == true {
                if inBrace {
                    switch char {
                        case "\\":
                            escape = true
                        case ">":
                            inBrace = false
                            str.append(char)
                        default:
                            str.append(char)
                    }
                } else {
                    switch char {
                    case "\\":
                        escape = true
                    case "\"":
                        tokens.append(str)
                        str = ""
                        inQuote = false
                    case "<":
                        inBrace = true
                        str.append(char)
                    default:
                        str.append(char)
                    }
                }
            } else if inQuote == false {
                switch char {
                case "\"":
                    inQuote = true
                case " ", "\t", "\r", "\n", "\r\n":
                    if str.isEmpty == false {
                        tokens.append(str)
                        str = ""
                    }
                case "=":
                    if str.isEmpty == false {
                        tokens.append(str)
                        str = ""
                    }
                    tokens.append(String(char))
                default:
                    str.append(char)
                }
            }
        }

        if str.isEmpty == false {
            tokens.append(str)
        }

        var attributes = [XmlAttribute]()
        var name = ""
        var expectValue = false
        for (_, token) in tokens[1..<tokens.count].enumerated() {
            if name.isEmpty {
                name = token
            } else if token == "=" {
                expectValue = true
            } else if expectValue == true {
                let attr = XmlAttribute(name: name, value: token)
                expectValue = false
                attributes.append(attr)
                name = ""
            } else {
                let attr = XmlAttribute(name: name)
                attributes.append(attr)
                name = token
            }
        }
        if name.isEmpty == false {
            let attr = XmlAttribute(name: name)
            attributes.append(attr)
        }

        let sep = tokens[0].split(separator: ":")
        if sep.count > 1 {
            return XmlElement(namespace: String(sep[0]), name: String(sep[1]), attributes: attributes)
        } else {
            return XmlElement(name: String(sep[0]), attributes: attributes)
        }
    }

**Comment by bjtj** [comment]
I'm investigating it.

Thanks

**Comment by bjtj** [comment]
I fixed the issue and updated the tags.

- https://github.com/bjtj/swift-xml/releases/tag/0.1.14
- https://github.com/bjtj/swift-upnp-tools/releases/tag/0.1.22

Thanks,

**Comment by meisbedi** [comment]
The fix works.
